### ISSUE TITLE
[TRACKING] Terminal and terminfo-related issues

### ISSUE THREAD

**Issue by apjanke** [apjanke/oh-my-zsh#2]
This is a tracking issue that collects links to the various oh-my-zsh issues and pull requests related to terminal configuration, terminfo, and key bindings.

##   Issues   ##

robbyrussell/oh-my-zsh#4213 – duplicate pwd in Terminal.app window title
robbyrussell/oh-my-zsh#4157 – safe-paste is unsafe in vi mode
robbyrussell/oh-my-zsh#4075 – tab completion in OS X 10.10 leaving extra characters
robbyrussell/oh-my-zsh#3757 – Home/End broken in PuTTY
robbyrussell/oh-my-zsh#3733 – Home/End broken in CentOS
robbyrussell/oh-my-zsh#3495 – Home/End broken in CentOS
robbyrussell/oh-my-zsh#3061 – Home/End broken in Ubuntu
robbyrussell/oh-my-zsh#2698 – Home/End broken in gnome-terminal
robbyrussell/oh-my-zsh#2696 – Home/End broken on OS X
robbyrussell/oh-my-zsh#3658 – hardcoded escapes in installer "echo"
robbyrussell/oh-my-zsh#3583 – Multibyte chars in Terminal.app pwd URLs get garbled
robbyrussell/oh-my-zsh#3435 – vi-mode plugin clobbers key bindings
robbyrussell/oh-my-zsh#3425 – urxvt portability problem with color escape sequences
robbyrussell/oh-my-zsh#3350 – Tab autocompletion not working for this user
robbyrussell/oh-my-zsh#3331 – ZOC incompatibility with xterm title-setting escape sequences
robbyrussell/oh-my-zsh#2750 – Cursor key bindings broken in `urxvt` on openSUSE
robbyrussell/oh-my-zsh#2735 – history-substring-search key bindings broken after `terminfo` changeover
~~robbyrussell/oh-my-zsh#2654 – Num keypad broken on OS X~~
~~robbyrussell/oh-my-zsh#2608 – "cannot bind to an empty key sequence" on OS X~~
robbyrussell/oh-my-zsh#2416 – "terminalapp plugin is broken and obsolete in mavericks"
robbyrussell/oh-my-zsh#2314 – Line Wrapping Bug
~~robbyrussell/oh-my-zsh#2369 – Change to option-arrow behavior on OS X~~
~~robbyrussell/oh-my-zsh#1433 – history-substring-search broken on Ubuntu 12.10~~

###   tmux / screen  issues   ###

robbyrussell/oh-my-zsh#3937  – broken colorscheme in tmux
robbyrussell/oh-my-zsh#3823  – artifacts in neovim embedded terminal due to forced `$TERM` in `.zshrc`
robbyrussell/oh-my-zsh#3645 – Emacs terminal emulator issues: artifacts after autocomplete
robbyrussell/oh-my-zsh#3579 – AUTO_TITLE broken in tmux

###   Pull Requests  ###

robbyrussell/oh-my-zsh#4251 – Fix completion waiting dots line wrapping
robbyrussell/oh-my-zsh#4193 – history-substring-search: bind arrows in both vi and emacs keymaps (after updating histsubstr from upstream)
robbyrussell/oh-my-zsh#4192 – history-substring-search: bind arrows in both vi and emacs keymaps 
robbyrussell/oh-my-zsh#4191 – vi-mode: remove broken line-init/finish widgets
robbyrussell/oh-my-zsh#3790 – iTerm2 profile control support
robbyrussell/oh-my-zsh#3761 – vi-mode changes, using terminal control sequences and bindings
robbyrussell/oh-my-zsh#3727 – selectability of choosing method of setting terminal titles
robbyrussell/oh-my-zsh#3664 – installer: use printf and terminfo for portability
robbyrussell/oh-my-zsh#3627 – "Better research history" that changes `lib/key-bindings`
robbyrussell/oh-my-zsh#3616 – vi-mode: adds more key bindings
robbyrussell/oh-my-zsh#3582 – Fold terminalapp plugin in to `lib/termsupport`
robbyrussell/oh-my-zsh#2875 – Remove `screen*` support from `lib/termsupport`
robbyrussell/oh-my-zsh#2805 – iTerm2 tab colorization
robbyrussell/oh-my-zsh#2739 – Term window title setting under cygwin prompt
robbyrussell/oh-my-zsh#2445 – "Fixing iTerm Tmux integration"
robbyrussell/oh-my-zsh#1907 – `lib/keybindings`: "rebind key for editor"
robbyrussell/oh-my-zsh#1629 – "Special" high-precedence key bindings using terminfo
robbyrussell/oh-my-zsh#1491 – screen: "Bugfix extracted cmd"

### Important Historical Pull Requests  ###

robbyrussell/oh-my-zsh#1355 – Change hardcoded escapes to `terminfo` lookups in `lib/keybindings`

**Comment by mcornella** [comment]
I suggest putting this up on the upstream repo as a tracking issue, see https://youtu.be/KDUtjZHIx44?t=1545

**Comment by apjanke** [comment]
Moved this to an upstream tracking issue: robbyrussell/oh-my-zsh#4344. Closing in favor of the upstream issue.

**Comment by apjanke** [comment]
@mcornella: Thanks for the link; that's a good video.
